version: '2'
services:
  cabin_db:
    image: mysql:latest
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    restart: always
    ports:
      - 3309:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: fundacion
      MYSQL_USER: user123
      MYSQL_PASSWORD: 123
